Feat: add option to ommit variants on SEOPLP
deco-cx/apps pull request #290
Opened 2024-01-09 16:46 UTC by IncognitaDev

2024-01-09 19:37 UTC, guitavano commented
Can you put the motivation behind this suggestion?

2024-01-09 19:58 UTC, IncognitaDev commented
I'am not fully into the motivation, but it has been requested multiple times by SEO agencies of our costumers, Like Torra and now Trisex.  

Its ralated with Google Rich Results, before, PDP has 10 products detected (https://search.google.com/test/rich-results/result?id=_6j9U24yHLNbrwIkC_LcUw), now with this change (in our custom seo section) its detected only one item, that its the required result (https://search.google.com/test/rich-results/result?id=bfaBuXvHxtQzQmV_XTY0rA).

2024-01-11 15:11 UTC, mcandeia requested changes

2024-01-11 15:11 UTC, mcandeia commented on commerce/sections/Seo/SeoPDP.tsx
> +function Section({ jsonLD, ommitVariants, ...props }: Props) {
```suggestion
function Section({ jsonLD,omitVariants, ...props }: Props) {
```

2024-01-11 15:11 UTC, mcandeia commented on commerce/sections/Seo/SeoPDP.tsx
> +  ommitVariants?: boolean;
```suggestion
 omitVariants?: boolean;
```

2024-01-11 15:11 UTC, mcandeia commented on commerce/sections/Seo/SeoPDP.tsx
> +  if (ommitVariants && jsonLD?.product.isVariantOf?.hasVariant) {
```suggestion
  if (omitVariants && jsonLD?.product.isVariantOf?.hasVariant) {
```

2024-01-17 20:17 UTC, mcandeia approved these changes
Fix formatting

2024-01-17 20:17 UTC, mcandeia commented on commerce/sections/Seo/SeoPDP.tsx
> +function Section({ jsonLD,omitVariants, ...props }: Props) {
```suggestion
function Section({ jsonLD, omitVariants, ...props }: Props) {
```

2024-01-17 20:17 UTC, mcandeia commented on commerce/sections/Seo/SeoPDP.tsx
> + omitVariants?: boolean;
```suggestion
   omitVariants?: boolean;
```

2024-01-17 21:41 UTC, merged