Ft/build with precompile
deco-cx/apps pull request #436
Opened 2024-02-29 12:32 UTC by hugo-ccabral

## What is this contribution about?

## Loom
> Record a quick screencast describing your changes to show the team and help reviewers.

## Link
> Please provide a link to a branch that demonstrates this pull request in action.

2024-02-29 12:38 UTC, hugo-ccabral commented on website/handlers/router.ts
>  };
Não mexi no arquivo, foi apenas identação do check

2024-03-01 18:51 UTC, mcandeia requested changes

2024-03-04 15:41 UTC, tlgimenes commented on platforms/kubernetes/common/cmds/build.ts
> +      denoJson.compilerOptions.jsx = "precompile";
if you add compilerOptions.jsx you also need to set jsxImportSource

2024-03-08 18:44 UTC, mcandeia approved these changes

2024-03-11 13:28 UTC, tlgimenes approved these changes

2024-03-11 13:36 UTC, merged