[ SEO | VTEX ] Add meta robots in SEO PLP and SEO PDP
deco-cx/apps pull request #440
Opened 2024-03-04 19:23 UTC by gabrielMatosBoubee

## What is this contribution about?

In this pr I add 
```js
<meta name="robots" content="index, follow">
```
in all pages who don't receive "noIndexing prop" and add use cases to don't follow in PLP and PDP

![image](https://github.com/deco-cx/apps/assets/108771428/a54a3d6b-8b90-4f0b-b446-3cdb65d9357a)

## Link to test 

https://www.embelleze.com/Neutralizante/TRATAMENTO/1568?map=c%2Cc%2CproductClusterIds

## Link to undestand better the use cases

https://app.liveseo.com.br/projeto/CB566/task/8439/128563/preview?key=iXYXeK8m2S9x5Bhe

2024-03-06 01:18 UTC, guitavano commented
@igorbrasileiro can you review that? as you are looking to seo

2024-03-07 21:19 UTC, igorbrasileiro commented
These components website/sections/Seo/Seo.tsx, commerce/sections/Seo/SeoPDP, commerce/sections/Seo/SeoPLP, std/sections/SEOPDP, std/sections/SEOPLP are deprecated.

Do it at website/sections/Seo/SeoV2.tsx, commerce/sections/SeoPDPV2.tsx and commerce/sections/SeoPLPV2.tsx

2024-03-07 21:20 UTC, igorbrasileiro requested changes
Do it at Seo components which the filename ends with `V2.tsx`, others without this suffix is deprecated!

2024-03-21 16:28 UTC, igorbrasileiro commented
Sorry, maintain your changes, but add them to the Seo components with V2 suffix.

2024-03-21 16:29 UTC, igorbrasileiro approved these changes

2024-03-21 16:35 UTC, merged