feat: choose whether to concatenate URL parameters in the redirect.
deco-cx/apps pull request #491
Opened 2024-03-28 18:20 UTC by jonathanwlopes

Greetings,

This PR adds the option for the user to choose whether they want to keep the parameters in the redirect or not.
The functionality was changed to add the feature for files loaded via CSV and through the dashboard.

One issue that is occurring is that in the admin panel, the option, although functional, is not being saved. I would need some assistance or correction for this.

![image](https://github.com/deco-cx/apps/assets/65980571/31735419-2b0a-4a78-bf28-58ca3c688fcd)
* In this image, I demonstrate that despite being active, if I make it public, it will work. However, after refreshing the page, it remains functional but the active status is not retained.

** The parameter combination was initially starting as true by default. In this PR, I've changed it to false because "from" leads to "to," and if the user wishes "from" to lead to "to" with parameters added, they can enable it.

See how it works (PT-BR):
https://www.loom.com/share/24b287d5634c42178c9a522fc20e5c37

2024-04-19 12:34 UTC, matheusgr requested changes

2024-04-19 12:34 UTC, matheusgr commented on website/handlers/redirect.ts
> +  keepQueryParameters?: boolean;
```suggestion
  discardQueryParameters?: boolean;
```

Current behavior keeps query parameters if they are present.

We should keep current behavior if this new parameter is `undefined`.

2024-04-19 12:34 UTC, matheusgr commented on website/handlers/redirect.ts
> +    const finalLocation = !queryString || !keepQueryParameters
```suggestion
    const finalLocation = !queryString || discardQueryParameters
```

2024-04-19 12:34 UTC, matheusgr commented on website/loaders/redirects.ts
> +        keepQueryParameters: redirect.keepQueryParameters,
```suggestion
        discardQueryParameters: redirect.discardQueryParameters,
```

2024-04-19 12:34 UTC, matheusgr commented on website/loaders/redirectsFromCsv.ts
> +      const parts = row.split(/[,;](?=(?:(?:[^"]*"){2})*[^"]*$)/);
avoid new separators. it may break current users.

```suggestion
      const parts = row.split(/,(?=(?:(?:[^"]*"){2})*[^"]*$)/);
```

2024-05-07 17:49 UTC, guitavano commented
@jonathanwlopes can you check @matheusgr comments?

2024-05-14 15:52 UTC, jonathanwlopes commented
> @jonathanwlopes can you check @matheusgr comments?

@guitavano Yes, I just completed the verification and adaptation.
@matheusgr You're welcome for the suggestions.

2024-05-14 15:54 UTC, jonathanwlopes commented
@matheusgr @guitavano
can you validate if it's better now?

2024-06-12 21:05 UTC, matheusgr approved these changes

2024-06-12 21:06 UTC, matheusgr commented
> @matheusgr @guitavano can you validate if it's better now?

great work @jonathanwlopes!

proposal: maybe we could add some tests in another PR dealing with redirect. It will improve how we evaluate and discuss about this feature.

2024-06-25 18:14 UTC, merged