adicionando logica de mudar o min de scalling para pods sem serem em …
deco-cx/apps pull request #543
Opened 2024-04-23 20:15 UTC by vitortrindader

…prod

## What is this contribution about?

## Loom
> Record a quick screencast describing your changes to show the team and help reviewers.

## Link
> Please provide a link to a branch that demonstrates this pull request in action.

2024-04-24 11:34 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
>    );
coloca tudo isso dentro de um metodo pra esse daqui não ficar tão grande, vai ficar mais clean

2024-04-24 11:37 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
>    );
Além disso `oldProdRevision` pode ser undefined daí tu bota isso dentro de um IF para tratar esse caso

2024-04-24 11:37 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
> +      "serving.knative.dev",
Acho que vale criar um arquivo de constantes para colocar todas essas juntas, vai ajudar a reaproveitar para outros casos

2024-04-24 11:38 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
> +      "serving.knative.dev",
O "v1", "revisions", "routes" tb

2024-04-24 11:48 UTC, hugo-ccabral requested changes

2024-04-26 11:31 UTC, mcandeia requested changes

2024-04-26 11:31 UTC, mcandeia commented on platforms/kubernetes/actions/deployments/rollout.ts
> +    });
you're logging it here but what happens then? the currentProdRevision will be undefined and that's it? Is there any action that we should take?

2024-04-26 11:31 UTC, mcandeia commented on platforms/kubernetes/actions/deployments/rollout.ts
> +const updtadeOldRevision = async ({
How about create a separated file for this? I think there are a folder which contains knative utilities. You should consider have a

allowScaleToZero(revision); function that make the magic happen, move the entire logic to there

2024-04-26 11:31 UTC, mcandeia commented on platforms/kubernetes/actions/deployments/rollout.ts
> +  await updtadeOldRevision({ oldRevision, site, ctx });
We have a choice here.

1 - Or you should fail when you can't get the previous prod revision (then you can use `await` here)
2 - Or you don't care about that and you don't need to `await` here. It seems to be that we have a mixed solution, which you catch errors - and ignore them, but here you're "await" it. Let's simplify. how about not `await` here?

2024-04-26 11:31 UTC, mcandeia commented on platforms/kubernetes/actions/deployments/rollout.ts
> +  const oldProdRevisionBody = {
Keep naming consistent,

instead of `Current` vs `Old` use `New` vs `Old` or `Current` vs `Previous`.


I'd prefer `previousProdRevision`

2024-04-26 11:31 UTC, mcandeia commented on platforms/kubernetes/actions/deployments/rollout.ts
> +  const oldProdRevisionBody = {
Rename in all occurrences of `old`

2024-04-26 13:04 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
> +  GROUP_SERVINGKNATIVEDEV,
```suggestion
  GROUP_SERVING_KNATIVE_DEV,
```

2024-04-26 13:11 UTC, mcandeia approved these changes

2024-04-26 13:11 UTC, mcandeia commented on platforms/kubernetes/common/knative/utils.ts
> +import { upsertObject } from "../../common/objects.ts";
utils => revisions

2024-04-26 13:15 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
> +
Move isso pro arquivo relativo ao knative. Além disso esse é o body de qualquer revision e não apenas da current
`RevisionBody`

2024-04-26 13:18 UTC, hugo-ccabral commented on platforms/kubernetes/actions/deployments/rollout.ts
> +    currentProdRevision?.body as CurrentProdRevisionBody;
Acho que isso pode ir pra `getProdRevision` e ele já retorna um `RevisionBody`

2024-04-26 16:45 UTC, hugo-ccabral commented on platforms/kubernetes/common/knative/revisions.ts
> +  if (!revisionBody) {
Aqui é `revision` ao invés de `revisionBody`, pq o body sempre existirá tu criou logo aí acima

2024-04-26 16:46 UTC, hugo-ccabral commented on platforms/kubernetes/common/knative/revisions.ts
> +  revision: string;
Aqui é `string | undefined`?

2024-04-26 16:48 UTC, hugo-ccabral commented on platforms/kubernetes/common/objects.ts
> +export interface ProdRevisionBody {
Esse tipo não é especifico só pra `Prod`, deixa só `RevisionBody`, na real isso não é uma rota?

2024-04-26 16:49 UTC, hugo-ccabral requested changes
A few more nits

2024-04-27 10:11 UTC, hugo-ccabral commented on platforms/kubernetes/common/knative/revisions.ts
> +  if (!revision) {
eu quis dizer que aqui é `revisionName`

2024-04-27 10:12 UTC, hugo-ccabral commented on platforms/kubernetes/common/knative/revisions.ts
> +  if (!revision) {
isso pode até subir pra antes da definição do objeto

2024-04-29 14:54 UTC, hugo-ccabral approved these changes

2024-04-29 15:51 UTC, merged