Magento getcart
deco-cx/apps pull request #547
Opened 2024-04-25 17:09 UTC by devartes

## What is this contribution about?

2024-04-25 17:41 UTC, JonasJesus42 commented on magento/loaders/cart.ts
> +  }
Cria uma função que faz isso, ai não precisa do let orderForm

exemplo uma função que tem no app de VNDA 

```JS
  const getProductPrice = async (id: number): Promise<ProductPrice | null> => {
    if (!priceIntl) {
      return null;
    } else {
      try {
        const result = await api["GET /api/v2/products/:productId/price"]({
          productId: id,
        }, STALE);
        return result.json();
      } catch (_error) {
        return null;
      }
    }
  };
```

ai pode fazer um `const oderFrom = getCart(cartId)
`

2024-04-25 17:41 UTC, JonasJesus42 commented on magento/mod.ts
> +      Host: new URL(baseUrl).host,
verifica se precisa do headers

2024-04-25 17:41 UTC, JonasJesus42 commented on magento/mod.ts
> +      baseUrl,
não precisamos do baseUrl disponível no contexto

2024-04-25 17:41 UTC, JonasJesus42 commented on magento/utils/client/types.ts
> +  items: unknown[];
olha na Doc para ver qual a tipagem

2024-04-25 17:41 UTC, JonasJesus42 commented on magento/utils/client/types.ts
> +    shipping_assignments: unknown[];
aqui também, da uma olhada

2024-04-25 18:36 UTC, carcara-gustavo requested changes

2024-04-25 18:36 UTC, carcara-gustavo commented on magento/utils/cart.ts
> +};
Remover pois não esta sendo usado

2024-04-25 18:36 UTC, carcara-gustavo commented on magento/utils/cart.ts
> +const CART_COOKIE = "magento_cart_id";
O nome do cookie que tem o CartID é `dataservices_cart_id` da uma checada no site da Granado para ver como ele seta esse dado, se não me engano eles usam um encodeURI numa string tipo `"1231231312"` com as aspas, então é importante usar um decodeURI e remover as aspas antes de usar.

2024-04-25 18:36 UTC, carcara-gustavo commented on magento/utils/client/types.ts
> +  items: unknown[];
Adicionar produtos no carrinho, via API, para ver o JSON correto. Não cheque apenas a documentação

2024-04-25 18:36 UTC, carcara-gustavo commented on magento/mod.ts
> +      apiKey,
Nao precisa da apiKey no state, a autenticação deve estar nos header do createHttpClient

2024-04-25 18:39 UTC, carcara-gustavo commented on magento/loaders/cart.ts
> +  orderForm?: API["GET /rest/:site/V1/guest-carts/:cartId"]["response"];
Essa propriedade orderForm não é legal, seria mais facil de usar um retorno que fosse o proprio objeto de Carrinho com todas as propriedades dele, e não uma propriedade intermediaria

2024-04-26 21:05 UTC, devartes commented on magento/utils/segment.ts
removido, não estava sendo usado

2024-05-02 13:07 UTC, JonasJesus42 commented on magento/loaders/cart.ts
> +  if (cartDetails?.id) {
precisa do ? cartDetails?.id, olhando o código parece que o cartDetails nunca vai estar vazio

2024-05-02 13:09 UTC, JonasJesus42 commented on magento/mod.ts
>    api: ReturnType<typeof createHttpClient<API>>;
mude o nome de api para o tipo de client

2024-05-02 13:10 UTC, JonasJesus42 commented on magento/mod.ts
>    });
o nome esta clientGuest porem ele recebe o token de admin

2024-05-02 13:10 UTC, JonasJesus42 commented on magento/mod.ts
> +      api: clientGuest,
quando mudar o nome pode retirar essa chave valor e passar direto

2024-05-03 13:48 UTC, carcara-gustavo approved these changes

2024-05-03 17:44 UTC, merged