feat: create verified reviews loader and fix types
deco-cx/apps pull request #633
Opened 2024-05-31 20:11 UTC by pedrobernardina

## What is this contribution about?

Although the platform offers an extension to the PDP Loader to include Verified Reviews, it offers no way of sorting or fetching new reviews after the initial render. This PR creates a loader to be invoked on client side to fetch reviews on demand.

It also fixes some types.

2024-06-07 14:20 UTC, gabrielMatosBoubee requested changes

2024-06-25 19:13 UTC, guitavano commented on verified-reviews/utils/client.ts
> +    | "most_helpful";
Yes, @pedrobernardina can you keep older version and convert inside the function? We may have some stores with "date_ASC" saved on our panel, for example.

2024-07-26 13:52 UTC, matheusgr commented
@pedrobernardina can you reply the comments from @gabrielMatosBoubee ?

2024-08-29 17:30 UTC, guitavano commented
UP @pedrobernardina

2024-10-29 13:02 UTC, pedrobernardina commented
Hi guys, sorry for the (really) late reply. I'll check these comments and resume the work on this PR soon.

2024-12-02 13:50 UTC, pedrobernardina commented
@guitavano @gabrielMatosBoubee 

I'm closing this one because it's already included in #634 
I'll link this PR there to keep track of review comments.

2024-12-02 13:50 UTC, closed without merging