feat: add option to aggregate similar products to verified reviews
deco-cx/apps pull request #634
Opened 2024-05-31 20:28 UTC by pedrobernardina

In some segments it's common to register product variations as similar products instead of different SKUs. For instance, it's useful to register different colours of t-shirts as different products, otherwise the "colour - size" sku variations would be greater than some e-commerce support, although, in the end, they are the same product (e.g Camiseta Manga Curta Algodão Peruano). In these cases it's useful to aggregate the reviews of all similar products.

This PR makes some changes on the verified reviews loader and client in order to support this feature. The final rating is an weighted average of the rating of all similar products by their reviews count.

Obs: This branch was created from the one of #633 , so checking only the last commit will be easier to review the changes.

Obs2: There is a change on one method (client.reviews) that is breaking. The argument name was changed from "productId" to "productsIds", although we can add the latter as a new argument and change the logic a bit for it no to be breaking anymore.

This can be tested in the Admin by enabling the new option "aggregateSimilarProducts" and running the loader.

A local version (created on our repository) of both #633 and this PR can be seen in the preview bellow. 

https://deco-sites-simples-f7ec095wncm9.deno.dev/camiseta-manga-curta-algodao-peruano-branca-0077065014/p

2024-06-07 14:25 UTC, gabrielMatosBoubee requested changes

2024-06-07 14:25 UTC, gabrielMatosBoubee commented on verified-reviews/utils/transform.ts
> +  });
Use reduce: 

```js
const { weightedRating, totalRatings } = Object.entries(ratings ?? {}).reduce(
  (acc, [_, ratingDetails]) => {
    const count = Number(ratingDetails.count);
    const value = Number(parseFloat(ratingDetails.rate).toFixed(1));

    acc.totalRatings += count;
    acc.weightedRating += count * value;

    return acc;
  },
  { weightedRating: 0, totalRatings: 0 }
);
```

2024-07-26 13:52 UTC, matheusgr commented
@pedrobernardina Can you apply the @gabrielMatosBoubee suggestion?

2024-08-29 17:31 UTC, guitavano commented
Up @pedrobernardina

2024-12-17 19:09 UTC, matheusgr approved these changes

2024-12-17 19:10 UTC, merged