feat(blog): add related posts
deco-cx/apps pull request #976
Opened 2024-12-17 23:53 UTC by luanargolodev

## What is this contribution about?

This PR was made to add the option to search related posts.
The search is carried out according to the category/categories of the post.
An optional "excludeSlug" prop was also added to exclude the current post from the return list.

Example: 

<img width="1440" alt="Captura de Tela 2024-12-17 às 20 52 43" src="https://github.com/user-attachments/assets/c007aaa1-be79-4aaa-8e5b-5596d9b4b762" />

2024-12-18 00:25 UTC, IncognitaDev commented
Have you a link to admin were this is working? I want to see how the selection of `slug` is in the form, beside it, LGTM.

2025-01-06 15:19 UTC, matheusgr requested changes

2025-01-06 15:19 UTC, matheusgr commented on blog/utils/handlePosts.ts
> +  excludePostSlug?: string,
missing JSDoc

2025-01-06 15:19 UTC, matheusgr commented on blog/utils/handlePosts.ts
> +  const filteredPosts = filterPosts(posts, slug, term, excludePostSlug);
`excludePostSlug` is only being applied to `filterRelatedPosts`.

Filter this post slug from any result:

```suggestion
  const filteredPosts = filterPosts(posts, slug, term).filter(
      ({ slug: postSlug }) => postSlug !== excludePostSlug)
   );
```

2025-01-06 15:19 UTC, matheusgr commented on blog/loaders/BlogRelatedPosts.ts
> + */
JSDoc should be on the exported default function.

2025-01-06 15:19 UTC, matheusgr commented on blog/loaders/BlogRelatedPosts.ts
> + */
```suggestion
```

2025-01-06 15:19 UTC, matheusgr commented on blog/utils/handlePosts.ts
> +  slug?: string | string[],
missing JSDoc

 * @param slug Category slug or an array of slugs to be filtered

2025-01-06 19:14 UTC, matheusgr approved these changes

2025-01-06 19:14 UTC, merged